---
- name: OpenShift Node Provisioning Lifecycle Manager
  hosts: localhost

  sources:
    - sabre1041.eda.k8s:
        api_version: "machine.openshift.io/v1beta1"
        kind: "Machine"
        validate_certs: false

  rules:
    - name: Notify
      condition: event.type != ""
      action:
        debug:
          msg: "{{ event }}"                     
