---
- name: OpenShift Node Provisioning Lifecycle Manager
  hosts: localhost

  sources:
    - sabre1041.eda.k8s:
        host: "{{ k8s_host }}"
        api_key: "{{ k8s_token }}"
        validate_certs: false
        api_version: "machine.openshift.io/v1beta1"
        kind: "Machine"

  rules:
    - name: Notify
      condition: true
      action:
        debug:
          msg: "{{ event }}"                     
