---
- name: Watch for untrusted OpenShift nodes via Alertmanager
  hosts: localhost

  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Trigger validation for new untrusted node
      condition: event.alert.labels.alertname == 'UntrustedNodeProvisioned'
      action:
        run_job_template:
          name: "OCP4: Validate"
          organization: "Lab"
          job_args:
            extra_vars:
              node_name: "{{ event.alert.labels.node }}"
              node_ip: "{{ event.alert.labels.internal_ip }}"
