---
- name: OpenShift Node Provisioning Lifecycle Manager
  hosts: localhost

  sources:
    - sabre1041.eda.k8s:
        host: "{{ lookup('env', 'K8S_AUTH_HOST') }}"
        api_key: "{{ lookup('env', 'K8S_AUTH_API_KEY') }}"
        validate_certs: false
        api_version: "v1"
        kind: "Machine"

  rules:
    - name: Notify
      condition: true
      action:
        debug:
          msg: "{{ event }}"                     
